### PR TITLE
GitHub rate limit notice

### PR DESCRIPTION
**Pull request by CoolCanuck**

### CODE REVIEW

**Comment by KTibow** [comment]
Might want to change "will" to "may". It didn't take that long for me.

**Review by ludeeus — CHANGES_REQUESTED** [review]
This additional text should _only_ be shown on new installations.
This behavior is now also in the documentation https://hacs.xyz/docs/faq/initial_startup

**Comment by KTibow** [comment]
Off topic note: I know HACS is supposed to be simple, but this limit could be solved by using a torrent-like system, so people who already downloaded and want to support new installations could share their files.

**Comment by ludeeus** [comment]
Closing this for now, feel free to open a new one that only shows on the initial startup :+1:

**Pull request closed without merging**
