### PR TITLE
Create sk.json

### PR DESCRIPTION
**Pull request by misa1515**
Created template for new translation

### CODE REVIEW

**Comment by ludeeus** [comment]
Translations are all handled on localize https://hacs.xyz/docs/developer/translation

**Comment by misa1515** [comment]
@ludeeus thank you. I wrongly set something (I don´t know what was wrong), for that reason on localize I see only English and Czech. How may I add/see on lokalize too Slovak language for HACS, please?

**Comment by ludeeus** [comment]
What email did you use there?

**Comment by misa1515** [comment]
I used on localize salka.milan@googlemail.com

**Comment by ludeeus** [comment]
You can only select existing languages, sk was missing.
Its been added now <https://app.lokalise.com/project/854515055f679055040b37.42677693/?view=single&reference_lang_id=640&single_lang_id=799>

**Comment by misa1515** [comment]
Thank you. Translation done.
Have a nice weekend.

**Comment by ludeeus** [comment]
Awesome, thanks 🎉

**Comment by misa1515** [comment]
I not found few parts for translate, screenshots attached.
image
image
image
image
image
image

**Comment by ludeeus** [comment]
That's the old UI, everything about it was removed a long time ago.

**Comment by misa1515** [comment]
how can be switched to new UI, please? It was showed direct after december installation.

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/configuration/options
Enable experimental features

**Comment by misa1515** [comment]
thank you.

**Pull request closed without merging**
