### PR TITLE
Fix load issue in safari

### PR DESCRIPTION
**Pull request by ludeeus**
Closes hacs/integration#2094

### CODE REVIEW

**Comment by Reynders1** [comment]
Hi,

The fix doesn't seem to work. The HACS page doesn't load in Safari (but is Ok in Chrome).

**Comment by ludeeus** [comment]
it works

**Comment by weitheng** [comment]
Do we need to wait for a new release from the integration or is it fixed without us doing anything?

**Comment by ludeeus** [comment]
yes

**Pull request merged**
