### PR TITLE
Add translation missing sections.pending_repository_upgrade

### LINKED ISSUE #547: Translation problem with 'repository.note_downloaded'?
chrome console log error:
```
 [HACS.localize] Translation problem with 'repository.note_downloaded' for 'zh_Hans'
```
https://github.com/hacs/frontend/blob/970dc1ce09eb7b26eba4cdef9521da326868bc89/src/components/dialogs/hacs-download-dialog.ts#L155

https://github.com/hacs/frontend/commit/970dc1ce09eb7b26eba4cdef9521da326868bc89#diff-12d32693d296e25fbdd26131c267fc760fdb6dc1f558b4e426b97fab9e1f82a1L92
```
"note_installed": "When downloaded, this will be located in",
```

`note_downloaded` means `note_installed`?

### PR DESCRIPTION
**Pull request by duhow**
Fixes #547

### CODE REVIEW

**Comment by ludeeus** [comment]
What is this fixing?
The issue is closed, and nothing in the codebase is using this key?

**Comment by duhow** [comment]
image

Translation is missing and displays translation key text instead. This has been around for long time.

**Comment by ludeeus** [comment]
This does not fix/change anything, that is a part of the old UI which no longer exists here.
For that reason I'm closing this PR 👍

**Comment by ludeeus** [comment]
1: Enable Experimental features
2: Use English
3: Wait for new UI to be non-experimental.

**Pull request closed without merging**
